### ISSUE TITLE
Clearing selection throws error with timepicker configuration

### ISSUE THREAD

**Issue by David-Nischk** [Eonasdan/tempus-dominus#2614] opened 2022-07-28 10:52 UTC
### Prerequisites

- [X] I have [searched](https://github.com/Eonasdan/tempus-dominus/issues?q=is%3Aissue) for duplicate or closed issues.
- [X] I have validated my setup against the latest version on [StackBlitz](https://stackblitz.com/edit/tempus-dominus-v6-simple-setup).
- [X] I have read the [contributing guidelines](https://github.com/Eonasdan/tempus-dominus/blob/master/.github/CONTRIBUTING.md).

### Describe the issue

Clearing a selected time in viewMode 'clock' throws an Uncaught TypeError in `_updateCalendarHeader()`. This method is called by the clear action and it seems to be only intended for using with calender related configurations because it always calls above mentioned method (the showing element does not contain the class `date-container`). 
A simple if statement for `currentView != clock` in the action works for me.

My configuration is as follows:

`display: {
      viewMode: 'clock',
      components: {
        decades: false,
        year: false,
        month: false,
        date: false,
        hours: true,
        minutes: true,
        seconds: false,
      },
      buttons: {
        close: true,
        clear: true,
      },
    },`

### StackBlitz fork

https://stackblitz.com/edit/tempus-dominus-v6-simple-setup-ciybkz?file=index.js

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Firefox, Microsoft Edge

### What version of are you using? You can find this information from the sample StackBlitz.

6.0.0-beta9

### What your browser's locale? You can find this information from the sample StackBlitz.

de-DE

**Comment by Eonasdan** [comment] 2022-10-24 16:40
This looks like it's been fixed in the latest version

**Closed by Eonasdan** 2022-10-24 16:40 UTC

**Comment by rjaros** [comment] 2022-11-05 06:45
The problem is still there in the current version.

**Comment by Eonasdan** [comment] 2022-12-08 20:39
@rjaros please see #2720
