### ISSUE TITLE
Cannot change the month when using daysOfWeekDisabled

### ISSUE THREAD

**Issue by RenanITAO** [Eonasdan/tempus-dominus#2434] opened 2021-11-17 10:41 UTC
Buttons to navigate to the next/previous month are disabled when using daysOfWeekDisabled, as showed in [this StackBlitz](https://stackblitz.com/edit/tempus-dominus-v6-simple-setup-cwwjy7)

**Comment by Eonasdan** [comment] 2021-11-17 13:31
Duplicate of #2419

**Closed by Eonasdan** 2021-11-17 13:31 UTC
