### ISSUE TITLE
Month and year do not update when the display month change after using the time picker

### ISSUE THREAD

**Issue by AlexandreMcCune** [Eonasdan/tempus-dominus#2686] opened 2022-10-04 16:00 UTC
### Prerequisites

- [X] I have [searched](https://github.com/Eonasdan/tempus-dominus/issues?q=is%3Aissue) for duplicate or closed issues.
- [X] I have validated my setup against the latest version on [StackBlitz](https://stackblitz.com/edit/tempus-dominus-v6-simple-setup).
- [X] I have read the [contributing guidelines](https://github.com/Eonasdan/tempus-dominus/blob/master/.github/CONTRIBUTING.md).

### Describe the issue

Step-by-step to replicate the bug:

- Open the datetime picker
- Change month, so you do not display the month of the selected date
- Open the time picker and change the time
- Collapse the time picker to see the calendar

At that point, the calendar display the month of the selected date, but the label at the top still display the month previously displayed.

### StackBlitz fork

https://stackblitz.com/edit/tempus-dominus-v6-simple-setup-pphjdf?embed=1&file=index.js

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Firefox, Microsoft Edge

### What version of are you using? You can find this information from the sample StackBlitz.

v6.2.4

### What your browser's locale? You can find this information from the sample StackBlitz.

en-CA

**Comment by shamarin** [comment] 2022-10-17 06:43
The same situation. Also found if to select month selecter and select it then if to change month by arrows month changes as should be at the label

**Comment by Eonasdan** [comment] 2022-11-03 22:56
This ends up being a duplicate of #2685. I'll have a fix branch soon that you can try. Please follow progress there.

**Closed by Eonasdan** 2022-11-03 22:56 UTC
Labels: Type: Bug, State: Triage
