### ISSUE TITLE
Min/Max crossing month threshold disables selection of max month

### ISSUE THREAD

**Issue by josephcrowell** [Eonasdan/tempus-dominus#2486] opened 2022-02-07 00:58 UTC
- Operating system and version: Windows 10 and Android and iOS
- Browser and version: Chrome, Firefox, Microsoft Edge
- Version of the plugin: 6

When the min and default date is for example Jan 31st 2022 and the max date is February 6 2022, the next month arrow button will be disabled and although you can click on dates from the next month, the selected date won't change when you click on them.

- Test and fork: https://stackblitz.com/edit/tempus-dominus-v6-simple-setup-jfh8ng

**Comment by josephcrowell** [comment] 2022-02-07 01:13
Also when you use the month selection drop down and select February, it selects March instead of February.

**Comment by josephcrowell** [comment] 2022-02-07 21:21
Is it possible that a datetime is being initialized with a 1 based month instead of 0 based somewhere?

**Comment by Eonasdan** [comment] 2022-02-08 00:30
turns out to be a duplicate of #2474. Please follow progress there.

**Closed by Eonasdan** 2022-02-08 00:30 UTC
Labels: bug
