### ISSUE TITLE
minDate option Error: this.optionsStore.options is undefined

### ISSUE THREAD

**Issue by reasecret** [Eonasdan/tempus-dominus#2865] opened 2023-10-03 23:25 UTC
### Prerequisites

- [X] I have [searched](https://github.com/Eonasdan/tempus-dominus/issues?q=is%3Aissue) for duplicate or closed issues.
- [X] I have validated my setup against the latest version on [StackBlitz](https://stackblitz.com/edit/tempus-dominus-v6-simple-setup).
- [X] I have read the [contributing guidelines](https://github.com/Eonasdan/tempus-dominus/blob/master/.github/CONTRIBUTING.md).

### Describe the issue

I'm trying to use minDate restriction like this: 
````
restrictions: {
                minDate: new Date(),
                maxDate: undefined,
                disabledDates: [],
                enabledDates: [],
                daysOfWeekDisabled: [],
                disabledTimeIntervals: [],
                disabledHours: [],
                enabledHours: []
            },
```` 
but getting this error:

`Uncaught TypeError: this.optionsStore.options is undefined `
[tempus-dominus.min.js:6:72541](https://cdn.jsdelivr.net/npm/@eonasdan/tempus-dominus@6.7.13/dist/js/tempus-dominus.min.js)

Tried v6.7.7 on StackBlitz and there is no error.

### StackBlitz fork

https://stackblitz.com/edit/tempus-dominus-v6-simple-setup-y8t7fn?file=index.js

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Firefox

### What version of are you using? You can find this information from the sample StackBlitz.

6.7.13

### What your browser's locale? You can find this information from the sample StackBlitz.

tr-Tr

**Comment by Eonasdan** [comment] 2023-10-06 21:38
duplicate of #2850

**Closed by Eonasdan** 2023-10-06 21:38 UTC
Labels: Type: Bug, State: Triage
