### ISSUE TITLE
Missing daysverrutscht englisch

### ISSUE THREAD

**Issue by ilovetacos** [Eonasdan/tempus-dominus#2475] opened 2022-01-26 11:49 UTC
Hi, I found an odd bug: in some months, there is the first or last day(s) missing. In the screenshot you can see that May 1st is missing. If I'd like to pick this date, I'd have to go back to April. A fix for this would be awesome! It only appears with the option startOfTheWeek: 1.

![missing_days](https://user-images.githubusercontent.com/8363697/151158282-0f1ec73a-46fb-44d0-9ede-e3068c4d5233.PNG)

- Operating system and version: Windows 10
- Browser and version Chrome 97.0.4692.99 and Firefox 96
- Version of the plugin: v6.0.0-beta2
- Stackblitz: https://stackblitz.com/edit/tempus-dominus-v6-simple-setup-2kvbn2

**Comment by William-H-M** [comment] 2022-01-26 22:37
Duplicate of #2473

**Closed by William-H-M** 2022-01-26 22:37 UTC
